d /etc/sanguinius 0700 root root -
d /opt/sanguinius 0755 root root -
d /opt/sanguinius/releases 0755 root root -
d /var/lib/sanguinius 0750 sanguinius sanguinius -
d /var/lib/sanguinius/runtime 0700 sanguinius sanguinius -
d /var/cache/sanguinius 0700 sanguinius sanguinius -
d /var/cache/sanguinius/tts 0700 sanguinius sanguinius -
d /var/log/sanguinius 0700 sanguinius sanguinius -
d /var/backups/sanguinius 0700 root root -
