if(NOT DEFINED INPUT_FILE OR NOT DEFINED OLD_RPATH OR NOT DEFINED NEW_RPATH)
    message(FATAL_ERROR "INPUT_FILE, OLD_RPATH, and NEW_RPATH are required")
endif()

file(RPATH_CHANGE
    FILE "${INPUT_FILE}"
    OLD_RPATH "${OLD_RPATH}"
    NEW_RPATH "${NEW_RPATH}"
)
